// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmallTax.Data;

namespace SmallTax.Data.Migrations
{
    [DbContext(typeof(TaxContext))]
    [Migration("20210426135829_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmallTax.Data.Entities.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Lower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Upper")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxBrackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lower = 1m,
                            Rate = 10m,
                            Upper = 8350m
                        },
                        new
                        {
                            Id = 2,
                            Lower = 8351m,
                            Rate = 15m,
                            Upper = 33950m
                        },
                        new
                        {
                            Id = 3,
                            Lower = 33951m,
                            Rate = 25m,
                            Upper = 82250m
                        },
                        new
                        {
                            Id = 4,
                            Lower = 82251m,
                            Rate = 28m,
                            Upper = 171550m
                        },
                        new
                        {
                            Id = 5,
                            Lower = 171551m,
                            Rate = 33m,
                            Upper = 372950m
                        },
                        new
                        {
                            Id = 6,
                            Lower = 37951m,
                            Rate = 35m,
                            Upper = -1m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
